import { AgentMetricDefinitionSchema } from '../schemas/agent-metric.schema.js';

export const agentForecastOutputRegistry = AgentMetricDefinitionSchema.array().parse([
  {
    id: 'forecast_operating_profit_amount',
    name: '预测经营利润',
    aliases: ['预测利润', '经营利润预测', '预测经营利润额', 'forecast_operating_profit_amount'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '基于调用方提供的终极变动成本率、终极固定成本率和已赚率计划做确定性情景计算的经营预测输出。',
    formula: '签单保费 × (100% - 终极变动成本率 - 终极固定成本率)',
    sourceMetrics: [
      'signed_premium',
      'ultimate_variable_cost_ratio',
      'ultimate_fixed_cost_ratio',
      'earning_schedule',
    ],
    sourceEndpoints: ['/api/agent/forecast/profit-scenario'],
    sourceRoutes: ['server/src/agent/routes/agent-forecast.ts'],
    sourceSqlGenerators: [],
    requiredParams: [
      'premium',
      'ultimateVariableCostRatio',
      'ultimateFixedCostRatio',
      'earningSchedule',
    ],
    supportedDimensions: [],
    supportedUseCases: ['forecast_operating_profit_scenario'],
    cautionNotes: ['基于调用方假设的情景计算，不是财务报表利润。'],
    forbiddenInterpretations: ['财务报表利润', '法定承保利润', '审计利润', '承保利润'],
    metricKind: 'forecast_output',
    metricNature: 'forecast_output',
    forecastRole: 'output',
    requiresAssumptions: true,
    actualFinancialInterpretation: 'forbidden',
  },
  {
    id: 'forecast_operating_profit_by_segment',
    name: '分群预测经营利润',
    aliases: ['分群利润预测', '机构利润预测', '客户类别利润预测', 'forecast_operating_profit_by_segment'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '在维度白名单（org_level_3 / customer_category / coverage_combination / salesman_name）内按分群独立传递成本率假设，做并行确定性情景计算的经营预测输出。仅向 branch_admin 开放。',
    formula: '每分群：签单保费 × (100% - 终极变动成本率 - 终极固定成本率)；汇总：保费加权终极综合成本率',
    sourceMetrics: [
      'forecast_operating_profit_amount',
    ],
    sourceEndpoints: ['/api/agent/forecast/profit-segment'],
    sourceRoutes: ['server/src/agent/routes/agent-forecast.ts'],
    sourceSqlGenerators: [],
    requiredParams: [
      'scenarioName',
      'dimension',
      'segments',
    ],
    supportedDimensions: [
      'org_level_3',
      'customer_category',
      'coverage_combination',
      'salesman_name',
    ],
    supportedUseCases: ['forecast_operating_profit_segment'],
    cautionNotes: [
      '基于调用方逐分群假设的情景计算，不是财务报表利润。',
      '仅向 branch_admin 开放；其他角色请使用单情景接口。',
    ],
    forbiddenInterpretations: ['财务报表利润', '法定承保利润', '审计利润', '承保利润'],
    metricKind: 'forecast_output',
    metricNature: 'forecast_output',
    forecastRole: 'output',
    requiresAssumptions: true,
    actualFinancialInterpretation: 'forbidden',
  },
]);
