import type { AgentMetricDefinition } from '../schemas/agent-metric.schema.js';
import { AgentMetricDefinitionSchema } from '../schemas/agent-metric.schema.js';

const COST_ENDPOINT = '/api/query/cost';
const COST_ROUTE = 'server/src/routes/query/cost.ts';
const COST_RATIO_SQL = 'server/src/sql/cost/cost-ratios.ts';
const COST_METRIC_REGISTRY = 'server/src/config/metric-registry/categories/cost.ts';
const COMPREHENSIVE_ROUTE = 'server/src/routes/query/comprehensive.ts';
const COMPREHENSIVE_SQL = 'server/src/sql/comprehensive-analysis.ts';

const PROFIT_MARGIN_FORBIDDEN = ['承保利润', '利润率', '盈利', '亏损', '财务盈利', '财务亏损'];
const MARGIN_FORBIDDEN = ['承保利润', '财务利润', '净利润', '财务盈亏'];
const MARGIN_CAUTION =
  '边际贡献额仅扣除变动成本（赔付+费用），不等于承保利润（后者还需扣固定成本/准备金/再保/税费）。';
const CAUTION_COST_FORBIDDEN = ['承保利润', '财务综合成本率', '完整综合成本率', '盈亏判断', '利润率'];

export const agentMetricRegistry = AgentMetricDefinitionSchema.array().parse([
  {
    id: 'signed_premium',
    name: '签单保费',
    aliases: ['总保费', '保费', '签单规模'],
    category: 'premium',
    supportLevel: 'supported',
    businessDefinition: '按项目现有 PolicyFact 保费字段聚合的签单保费经营规模指标。',
    formula: 'SUM(premium)',
    sourceMetrics: ['total_premium'],
    sourceEndpoints: ['/api/query/kpi', '/api/query/growth'],
    sourceRoutes: ['server/src/routes/query/kpi.ts', 'server/src/routes/query/growth.ts'],
    sourceSqlGenerators: ['generateGrowthQuery'],
    requiredParams: [],
    supportedDimensions: ['date', 'org_level_3', 'salesman_name', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['business_patrol_diagnosis', 'growth_diagnosis'],
    cautionNotes: ['用于经营规模分析，不代表财务收入确认口径。'],
    forbiddenInterpretations: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'policy_count',
    name: '保单件数',
    aliases: ['件数', '保单数'],
    category: 'premium',
    supportLevel: 'supported',
    businessDefinition: '按项目现有去重保单号口径统计保单件数。',
    formula: 'COUNT(DISTINCT policy_no)',
    sourceMetrics: ['policy_count'],
    sourceEndpoints: ['/api/query/kpi', COST_ENDPOINT],
    sourceRoutes: ['server/src/routes/query/kpi.ts', COST_ROUTE],
    sourceSqlGenerators: ['generateClaimRatioQuery', 'generateVariableCostQuery'],
    requiredParams: [],
    supportedDimensions: ['date', 'org_level_3', 'salesman_name', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['business_patrol_diagnosis', 'growth_diagnosis', 'cost_indicator_diagnosis'],
    cautionNotes: ['不同专题可能存在保单去重粒度差异，解释时必须跟随接口口径。'],
    forbiddenInterpretations: ['承保利润', '利润率'],
  },
  {
    id: 'growth_rate',
    name: '增长率',
    aliases: ['同比', '环比', '同比增长率', '环比增长率'],
    category: 'growth',
    supportLevel: 'supported',
    businessDefinition: '基于现有增长分析查询的同比、环比或自定义基期增长指标。',
    formula: '(本期 - 基期) / 基期',
    sourceMetrics: ['growth_rate_yoy', 'growth_rate_mom'],
    sourceEndpoints: ['/api/query/growth'],
    sourceRoutes: ['server/src/routes/query/growth.ts'],
    sourceSqlGenerators: ['generateGrowthQuery', 'generateDailyGrowthWithContextQuery'],
    requiredParams: ['growthType', 'timeView'],
    supportedDimensions: ['date', 'org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['growth_diagnosis', 'business_patrol_diagnosis'],
    cautionNotes: ['自定义基期问题必须显式传入 currentPeriod 和 baselinePeriod。'],
    forbiddenInterpretations: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'earned_premium',
    name: '满期/已赚保费',
    aliases: ['满期保费', '已赚保费'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '按项目成本 SQL 的闰年感知满期天数口径计算的经营分析分母。',
    formula: '保费 × 满期天数 / 保险期限天数',
    sourceMetrics: ['earned_premium'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE],
    sourceSqlGenerators: ['generateEarnedPremiumQuery', 'generateClaimRatioQuery', 'generateVariableCostQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination', 'org_customer', 'org_coverage'],
    supportedUseCases: ['cost_indicator_diagnosis'],
    cautionNotes: ['按项目现有 SQL 口径解释，不外推为完整财务已赚保费。'],
    forbiddenInterpretations: ['承保利润', '完整财务收入', '财务盈利', '财务亏损'],
  },
  {
    id: 'reported_claims',
    name: '已报告赔款',
    aliases: ['赔款', '报案赔款', '已报赔款'],
    category: 'claim',
    supportLevel: 'supported',
    businessDefinition: '成本与赔案查询中使用的已报告赔款经营分析口径。',
    sourceEndpoints: [COST_ENDPOINT, '/api/query/claims-detail/pending-overview'],
    sourceRoutes: [COST_ROUTE, 'server/src/routes/query/claims-detail.ts'],
    sourceSqlGenerators: ['generateClaimRatioQuery', 'generateVariableCostQuery', 'generatePendingOverviewQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
    cautionNotes: ['赔款口径来自项目 ClaimsAgg/ClaimsDetail 当前快照，不代表完整准备金精算口径。'],
    forbiddenInterpretations: ['承保利润', '财务亏损', '财务盈利'],
  },
  {
    id: 'claim_cases',
    name: '赔案件数',
    aliases: ['案件数', '赔案数'],
    category: 'claim',
    supportLevel: 'supported',
    businessDefinition: '用于案均赔款、出险频度和赔案风险诊断的赔案件数。',
    sourceEndpoints: [COST_ENDPOINT, '/api/query/claims-detail/frequency-yoy'],
    sourceRoutes: [COST_ROUTE, 'server/src/routes/query/claims-detail.ts'],
    sourceSqlGenerators: ['generateClaimRatioQuery', 'generateFrequencyYoyQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
    cautionNotes: ['不同赔案专题可能按报案、未决、出险原因等不同范围筛选。'],
    forbiddenInterpretations: ['承保利润', '利润率'],
  },
  {
    id: 'avg_claim_amount',
    name: '案均赔款',
    aliases: ['平均赔款', '件均赔款'],
    category: 'claim',
    supportLevel: 'supported',
    businessDefinition: '已报告赔款除以赔案件数，用于赔付结构与成本压力来源分析。',
    formula: '已报告赔款 / 赔案件数',
    sourceMetrics: ['avg_claim_amount'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE],
    sourceSqlGenerators: ['generateClaimRatioQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination', 'org_customer', 'org_coverage'],
    supportedUseCases: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
    cautionNotes: ['仅解释赔案强度，不单独推断利润或亏损。'],
    forbiddenInterpretations: ['承保利润', '财务亏损', '财务盈利', '利润率'],
  },
  {
    id: 'earned_claim_ratio',
    name: '满期赔付率',
    aliases: ['赔付率', '满期赔付率'],
    category: 'claim',
    supportLevel: 'supported',
    businessDefinition: '已报告赔款除以满期保费的项目经营分析赔付指标。',
    formula: '已报告赔款 / 满期保费',
    sourceMetrics: ['earned_claim_ratio'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE],
    sourceSqlGenerators: ['generateClaimRatioQuery', 'generateComprehensiveCostQuery', 'generateVariableCostQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination', 'org_customer', 'org_coverage'],
    supportedUseCases: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
    cautionNotes: ['不得直接解释为承保利润或财务亏损。'],
    forbiddenInterpretations: ['承保利润', '财务亏损', '财务盈利', '利润率'],
  },
  {
    id: 'earned_loss_frequency',
    name: '满期出险率',
    aliases: ['出险率', '满期频度', '出险频度'],
    category: 'risk',
    supportLevel: 'supported',
    businessDefinition: '按保险期限和满期天数年化后的出险频度指标。',
    formula: '(赔案件数/保单件数) × (保险期限天数/满期天数)',
    sourceMetrics: ['earned_loss_frequency'],
    sourceEndpoints: [COST_ENDPOINT, '/api/query/claims-detail/frequency-yoy'],
    sourceRoutes: [COST_ROUTE, 'server/src/routes/query/claims-detail.ts'],
    sourceSqlGenerators: ['generateClaimRatioQuery', 'generateFrequencyYoyQuery'],
    requiredParams: ['cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
    cautionNotes: ['用于风险频度解释，不输出盈利、亏损判断。'],
    forbiddenInterpretations: ['承保利润', '财务亏损', '财务盈利', '利润率'],
  },
  {
    id: 'expense_ratio',
    name: '费用率',
    aliases: ['手续费率', '费用占比'],
    category: 'expense',
    supportLevel: 'supported',
    businessDefinition: '费用金额除以签单保费的项目经营费用指标。',
    formula: '费用金额 / 签单保费',
    sourceMetrics: ['expense_ratio'],
    sourceEndpoints: [COST_ENDPOINT, '/api/query/expense-development'],
    sourceRoutes: [COST_ROUTE, 'server/src/routes/query/expense-development.ts'],
    sourceSqlGenerators: ['generateExpenseRatioQuery', 'generateVariableCostQuery', 'generateExpenseRatioDevelopmentQuery'],
    requiredParams: [],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
    cautionNotes: ['不得直接解释为完整费用分摊或承保利润。'],
    forbiddenInterpretations: ['承保利润', '完整费用分摊', '财务亏损', '财务盈利', '利润率'],
  },
  {
    id: 'variable_cost_ratio',
    name: '变动成本率',
    aliases: ['变动成本', '经营变动成本率'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '当前系统内经营分析指标，按项目现有成本 SQL 生成器口径计算。',
    formula: '项目现有 SQL 口径：满期赔付率 + 费用率',
    sourceMetrics: ['variable_cost_ratio', 'earned_claim_ratio', 'expense_ratio'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE, COST_RATIO_SQL],
    sourceSqlGenerators: ['generateVariableCostQuery'],
    requiredParams: ['analysisType=variableCost', 'cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination', 'org_customer', 'org_coverage'],
    supportedUseCases: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
    metricNature: 'observed',
    forecastRole: 'input',
    cautionNotes: [
      '这是项目内经营分析口径。',
      '不代表完整财务综合成本率。',
      '不包含完整准备金、再保、税费、固定费用分摊等财务或精算口径。',
    ],
    forbiddenInterpretations: ['承保利润', '利润率', '盈利', '亏损', '财务亏损', '财务盈利', '财务综合成本率'],
    replacementSuggestions: ['如需经营成本压力，拆解查看满期赔付率、费用率和变动成本率。'],
  },
  {
    id: 'quote_conversion_rate',
    name: '报价转化率',
    aliases: ['承保率', '报价承保率', '转化率'],
    category: 'quote',
    supportLevel: 'supported',
    businessDefinition: '报价清单专题中报价到承保的转化指标。',
    sourceMetrics: ['underwriting_rate'],
    sourceEndpoints: ['/api/query/quote-conversion/kpi', '/api/query/quote-conversion/funnel'],
    sourceRoutes: ['server/src/routes/query/quote-conversion.ts'],
    sourceSqlGenerators: ['generateQuoteKpiQuery', 'generateQuoteFunnelQuery'],
    requiredParams: [],
    supportedDimensions: ['orgName', 'teamName', 'salesmanNo', 'customerCategory', 'insuranceCombo'],
    supportedUseCases: ['quote_conversion_diagnosis', 'business_patrol_diagnosis'],
    cautionNotes: ['仅适用于报价转化专题，不替代承保利润分析。'],
    forbiddenInterpretations: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'renewal_tracker_metrics',
    name: '续保追踪指标',
    aliases: ['续保率', '续保追踪', '续转保'],
    category: 'renewal',
    supportLevel: 'supported',
    businessDefinition: '基于 renewal-tracker 当前到期和续保追踪口径的 A/B/C 指标集合。',
    sourceEndpoints: ['/api/query/renewal-tracker'],
    sourceRoutes: ['server/src/routes/query/renewal-tracker.ts'],
    sourceSqlGenerators: ['generateRenewalTrackerQuery'],
    requiredParams: ['start', 'end', 'cutoff'],
    supportedDimensions: ['orgNames', 'salesmanNames', 'customerCategories', 'coverageCombinations', 'fuelCategories'],
    supportedUseCases: ['renewal_tracker_diagnosis', 'business_patrol_diagnosis'],
    cautionNotes: ['使用 renewal-tracker 当前指标，不使用已下线 renewal funnel/v2。'],
    forbiddenInterpretations: ['承保利润', '利润率', '财务亏损', '财务盈利'],
  },
  {
    id: 'customer_inflow',
    name: '客户流入',
    aliases: ['转入', '流入客户'],
    category: 'customer_flow',
    supportLevel: 'supported',
    businessDefinition: '客户来源去向专题中的客户流入指标。',
    sourceEndpoints: ['/api/query/customer-flow/inflow', '/api/query/customer-flow/summary'],
    sourceRoutes: ['server/src/routes/query/customer-flow.ts'],
    sourceSqlGenerators: ['generateInflowQuery', 'generateFlowSummaryQuery'],
    requiredParams: [],
    supportedDimensions: ['year'],
    supportedUseCases: ['customer_flow_diagnosis'],
    cautionNotes: ['用于客户迁徙诊断，不输出盈利亏损结论。'],
    forbiddenInterpretations: ['承保利润', '利润率', '财务亏损', '财务盈利'],
  },
  {
    id: 'customer_outflow',
    name: '客户流出',
    aliases: ['流失', '转出', '流出客户'],
    category: 'customer_flow',
    supportLevel: 'supported',
    businessDefinition: '客户来源去向专题中的客户流出指标。',
    sourceEndpoints: ['/api/query/customer-flow/outflow', '/api/query/customer-flow/trend'],
    sourceRoutes: ['server/src/routes/query/customer-flow.ts'],
    sourceSqlGenerators: ['generateOutflowQuery', 'generateFlowTrendQuery'],
    requiredParams: [],
    supportedDimensions: ['year'],
    supportedUseCases: ['customer_flow_diagnosis'],
    cautionNotes: ['用于客户迁徙诊断，不输出盈利亏损结论。'],
    forbiddenInterpretations: ['承保利润', '利润率', '财务亏损', '财务盈利'],
  },
  {
    id: 'comprehensive_cost_ratio',
    name: '综合费用率/综合成本相关历史指标',
    aliases: ['综合费用率', '综合成本率', 'comprehensiveCost'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '项目 cost 模块已有 comprehensiveCost 历史经营指标审阅口径。',
    formula: '项目已有 SQL 口径：(赔款 + 费用) / 满期保费',
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE, COST_RATIO_SQL],
    sourceSqlGenerators: ['generateComprehensiveCostQuery'],
    requiredParams: ['analysisType=comprehensiveCost', 'cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination', 'org_customer', 'org_coverage'],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有经营指标审阅，不得解释为完整财务综合成本率。'],
    forbiddenInterpretations: ['承保利润', '财务综合成本率', '利润率', '盈亏判断'],
    replacementSuggestions: ['经营成本压力请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio 分别分析。'],
  },
  {
    id: 'earned_profit_amount',
    name: '利润额',
    aliases: ['利润额', '满期利润额', 'earned_profit_amount'],
    category: 'cost',
    supportLevel: 'unsupported',
    businessDefinition: '底层成本指标注册表已有的 L4 利润额指标；Agent 层禁止输出或推断该类利润、盈利、亏损结论。',
    formula: '底层注册表口径：满期保费 - 综合成本额',
    sourceMetrics: ['earned_profit_amount'],
    sourceEndpoints: [],
    sourceRoutes: [COST_METRIC_REGISTRY],
    sourceSqlGenerators: [],
    requiredParams: [],
    supportedDimensions: [],
    supportedUseCases: [],
    cautionNotes: ['底层指标注册表存在不等于 Agent 可以输出利润、边际贡献或盈亏结论。'],
    forbiddenInterpretations: PROFIT_MARGIN_FORBIDDEN,
    replacementSuggestions: ['如需经营成本压力，请使用变动成本率（variable_cost_ratio）、满期赔付率（earned_claim_ratio）、费用率（expense_ratio）分别分析。'],
  },
  {
    id: 'earned_margin_amount',
    name: '满期边际贡献额',
    aliases: ['满期边际贡献额', '边际贡献额', 'earned_margin_amount'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '底层成本指标注册表已有的 L4 边际贡献类经营指标，仅扣除变动成本，不是承保利润或财务利润。',
    formula: '底层注册表口径：满期保费 × (1 - 满期赔付率 - 费用率)',
    sourceMetrics: ['earned_margin_amount'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE, COST_METRIC_REGISTRY],
    sourceSqlGenerators: ['generateComprehensiveCostQuery'],
    requiredParams: ['analysisType=comprehensiveCost', 'cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'comprehensive_cost_indicator_review'],
    metricNature: 'observed',
    forecastRole: 'none',
    cautionNotes: [MARGIN_CAUTION],
    forbiddenInterpretations: MARGIN_FORBIDDEN,
  },
  {
    id: 'projected_margin_amount',
    name: '预估边际贡献额',
    aliases: ['预估边际贡献额', '预计边际贡献', 'projected_margin_amount'],
    category: 'cost',
    supportLevel: 'supported',
    businessDefinition: '底层成本指标注册表已有的 L4 预估边际贡献经营指标，仅扣除变动成本，不是承保利润或财务利润。',
    formula: '底层注册表口径：签单保费 × (1 - 满期赔付率 - 费用率)',
    sourceMetrics: ['projected_margin_amount'],
    sourceEndpoints: [COST_ENDPOINT],
    sourceRoutes: [COST_ROUTE, COST_METRIC_REGISTRY],
    sourceSqlGenerators: ['generateComprehensiveCostQuery'],
    requiredParams: ['analysisType=comprehensiveCost', 'cutoffDate'],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['cost_indicator_diagnosis', 'comprehensive_cost_indicator_review'],
    metricNature: 'observed',
    forecastRole: 'none',
    cautionNotes: [MARGIN_CAUTION],
    forbiddenInterpretations: MARGIN_FORBIDDEN,
  },
  {
    id: 'comprehensive_expense_ratio',
    name: '综合费用率',
    aliases: ['综合费用率', 'comprehensive_expense_ratio'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '底层成本指标注册表和综合分析中已有的扩展经营成本指标，只能作为 caution 审阅。',
    formula: '底层注册表口径：(已报告赔款 + 费用金额) / 满期保费',
    sourceMetrics: ['comprehensive_expense_ratio'],
    sourceEndpoints: ['/api/query/comprehensive-analysis-bundle'],
    sourceRoutes: [COST_METRIC_REGISTRY, COMPREHENSIVE_ROUTE, COMPREHENSIVE_SQL],
    sourceSqlGenerators: ['generateComprehensiveDimensionMetricsQuery', 'generateComprehensiveSummaryQuery'],
    requiredParams: [],
    supportedDimensions: ['org_level_3', 'customer_category', 'coverage_combination'],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有扩展经营成本口径审阅，不进入成本指标诊断主路径。'],
    forbiddenInterpretations: CAUTION_COST_FORBIDDEN,
    replacementSuggestions: ['成本诊断主路径请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio。'],
  },
  {
    id: 'fixed_cost_amount',
    name: '固定成本额',
    aliases: ['固定成本额', 'fixed_cost_amount'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '底层成本指标注册表已有的 L4 固定成本额指标，依赖外部固定成本参数。',
    formula: '底层注册表口径：附加税费额 + 推动费额 + 管理费额',
    sourceMetrics: ['fixed_cost_amount'],
    sourceEndpoints: [],
    sourceRoutes: [COST_METRIC_REGISTRY],
    sourceSqlGenerators: [],
    requiredParams: [],
    supportedDimensions: [],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有扩展经营成本口径审阅，不进入成本指标诊断主路径。'],
    forbiddenInterpretations: CAUTION_COST_FORBIDDEN,
    replacementSuggestions: ['成本诊断主路径请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio。'],
  },
  {
    id: 'fixed_cost_ratio',
    name: '固定成本率',
    aliases: ['固定成本率', 'fixed_cost_ratio'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '底层成本指标注册表已有的 L4 固定成本率指标，依赖外部固定成本参数。',
    formula: '底层注册表口径：固定成本额 / 满期保费',
    sourceMetrics: ['fixed_cost_ratio'],
    sourceEndpoints: [],
    sourceRoutes: [COST_METRIC_REGISTRY],
    sourceSqlGenerators: [],
    requiredParams: [],
    supportedDimensions: [],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有扩展经营成本口径审阅，不进入成本指标诊断主路径。'],
    forbiddenInterpretations: CAUTION_COST_FORBIDDEN,
    replacementSuggestions: ['成本诊断主路径请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio。'],
  },
  {
    id: 'combined_cost_amount',
    name: '综合成本额',
    aliases: ['综合成本额', 'combined_cost_amount'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '底层成本指标注册表已有的 L4 综合成本额指标，只能作为 caution 审阅。',
    formula: '底层注册表口径：变动成本额 + 固定成本额',
    sourceMetrics: ['combined_cost_amount'],
    sourceEndpoints: [],
    sourceRoutes: [COST_METRIC_REGISTRY],
    sourceSqlGenerators: [],
    requiredParams: [],
    supportedDimensions: [],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有扩展经营成本口径审阅，不进入成本指标诊断主路径。'],
    forbiddenInterpretations: CAUTION_COST_FORBIDDEN,
    replacementSuggestions: ['成本诊断主路径请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio。'],
  },
  {
    id: 'combined_cost_ratio',
    name: '综合成本率',
    aliases: ['综合成本率', 'combined_cost_ratio'],
    category: 'cost',
    supportLevel: 'caution',
    businessDefinition: '底层成本指标注册表已有的 L4 综合成本率指标，不代表完整财务综合成本率。',
    formula: '底层注册表口径：综合成本额 / 满期保费',
    sourceMetrics: ['combined_cost_ratio'],
    sourceEndpoints: [],
    sourceRoutes: [COST_METRIC_REGISTRY],
    sourceSqlGenerators: [],
    requiredParams: [],
    supportedDimensions: [],
    supportedUseCases: ['comprehensive_cost_indicator_review'],
    cautionNotes: ['仅作为项目已有扩展经营成本口径审阅，不进入成本指标诊断主路径。'],
    forbiddenInterpretations: CAUTION_COST_FORBIDDEN,
    replacementSuggestions: ['成本诊断主路径请使用 variable_cost_ratio、earned_claim_ratio、expense_ratio。'],
  },
  {
    id: 'expense_development_metrics',
    name: '费用发展指标',
    aliases: ['费用发展', '费用率发展'],
    category: 'expense',
    supportLevel: 'caution',
    businessDefinition: '费用率发展专题中的费用趋势和发展月指标。',
    sourceEndpoints: ['/api/query/expense-development'],
    sourceRoutes: ['server/src/routes/query/expense-development.ts'],
    sourceSqlGenerators: ['generateExpenseRatioDevelopmentQuery'],
    requiredParams: [],
    supportedDimensions: ['cohortYears', 'orgNames', 'customerCategories'],
    supportedUseCases: ['cost_indicator_diagnosis'],
    cautionNotes: ['可用于费用趋势和费用压力分析，不得外推为完整费用分摊或利润指标。'],
    forbiddenInterpretations: ['承保利润', '完整费用分摊', '利润率', '盈亏判断'],
  },
] satisfies AgentMetricDefinition[]);
