import type { AgentCapabilityDefinition } from '../schemas/agent-capability.schema.js';
import { AgentCapabilityDefinitionSchema } from '../schemas/agent-capability.schema.js';

export const agentDataCapabilityRegistry = AgentCapabilityDefinitionSchema.array().parse([
  {
    id: 'business_patrol_diagnosis',
    name: '经营巡检',
    supportLevel: 'supported',
    description: '用于发现经营指标异常和下钻方向。',
    coreMetrics: ['signed_premium', 'policy_count', 'growth_rate', 'earned_claim_ratio', 'expense_ratio', 'variable_cost_ratio', 'quote_conversion_rate', 'renewal_tracker_metrics'],
    sourceEndpoints: ['/api/agent/diagnosis/business-patrol', '/api/query/cost', '/api/query/growth', '/api/query/quote-conversion/kpi', '/api/query/renewal-tracker', '/api/query/claims-detail/pending-overview', '/api/query/customer-flow/summary'],
    sourceTools: ['business_patrol.query', 'growth.query', 'cost.variable_cost', 'cost.claim_ratio', 'cost.expense_ratio', 'quote_conversion.kpi', 'renewal_tracker.query', 'claims_detail.pending_overview', 'customer_flow.summary'],
    allowedUseCases: ['经营异常识别', '指标下钻建议', '成本压力提示'],
    cautionNotes: ['不输出承保利润、盈利、亏损。'],
    forbiddenOutputs: ['承保利润', '盈利', '亏损', '利润率'],
  },
  {
    id: 'growth_diagnosis',
    name: '增长归因',
    supportLevel: 'supported',
    description: '分析保费增长或下滑来源。',
    coreMetrics: ['signed_premium', 'policy_count', 'growth_rate'],
    sourceEndpoints: ['/api/query/growth'],
    sourceTools: ['growth.query', 'growth.daily_context'],
    allowedUseCases: ['同比分析', '环比分析', '自定义基期增长分析'],
    cautionNotes: ['增长不是利润，不能推断财务盈亏。'],
    forbiddenOutputs: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'cost_indicator_diagnosis',
    name: '成本指标诊断',
    supportLevel: 'supported',
    description: '基于当前项目已有成本指标做经营诊断。',
    coreMetrics: ['earned_premium', 'reported_claims', 'claim_cases', 'avg_claim_amount', 'earned_claim_ratio', 'earned_loss_frequency', 'expense_ratio', 'variable_cost_ratio', 'earned_margin_amount', 'projected_margin_amount'],
    sourceEndpoints: ['/api/query/cost', '/api/query/expense-development'],
    sourceTools: ['cost.variable_cost', 'cost.claim_ratio', 'cost.expense_ratio', 'cost.earned_premium'],
    allowedUseCases: ['成本类经营指标诊断', '赔付与费用联动分析', '机构和客户类别维度对比'],
    cautionNotes: ['本能力分析的是项目内经营成本指标，不是完整财务承保利润分析。'],
    forbiddenOutputs: ['承保利润', '利润率', '财务亏损', '财务盈利'],
  },
  {
    id: 'forecast_operating_profit_scenario',
    name: '经营利润预测情景测算',
    supportLevel: 'supported',
    description: '基于调用方提供的终极变动成本率、终极固定成本率和已赚率计划，做确定性经营利润预测。',
    coreMetrics: [
      'signed_premium',
      'ultimate_variable_cost_ratio',
      'ultimate_fixed_cost_ratio',
      'ultimate_combined_cost_ratio',
      'forecast_operating_profit_amount',
      'forecast_profit_sensitivity_per_1pct',
    ],
    sourceEndpoints: ['/api/agent/forecast/profit-scenario'],
    sourceTools: ['forecast.profit_scenario'],
    allowedUseCases: ['终极成本率情景测算', '经营利润预测', '成本率敏感性分析', '盈亏平衡测算'],
    cautionNotes: [
      '输出为经营预测利润，不是财务报表利润。',
      '必须展示终极变动成本率、终极固定成本率和已赚率假设。',
    ],
    forbiddenOutputs: ['法定承保利润', '审计利润', '财务净利润', '未注明口径的实际盈亏'],
  },
  {
    id: 'quote_conversion_diagnosis',
    name: '报价转化诊断',
    supportLevel: 'supported',
    description: '分析报价转化漏斗、转化卡点、机构/团队/业务员差异。',
    coreMetrics: ['quote_conversion_rate', 'quote funnel metrics'],
    sourceEndpoints: ['/api/query/quote-conversion/kpi', '/api/query/quote-conversion/funnel', '/api/query/quote-conversion/drilldown', '/api/query/quote-conversion/trend'],
    sourceTools: ['quote_conversion.kpi', 'quote_conversion.funnel', 'quote_conversion.drilldown', 'quote_conversion.trend'],
    allowedUseCases: ['报价漏斗分析', '转化卡点定位', '团队差异分析'],
    cautionNotes: ['转化率专题不输出财务盈利亏损。'],
    forbiddenOutputs: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'renewal_tracker_diagnosis',
    name: '续保追踪诊断',
    supportLevel: 'supported',
    description: '使用 renewal-tracker，不使用旧 renewal funnel/v2。',
    coreMetrics: ['renewal tracker metrics'],
    sourceEndpoints: ['/api/query/renewal-tracker'],
    sourceTools: ['renewal_tracker.query'],
    allowedUseCases: ['续保追踪', '到期车辆追踪', '机构/业务员续保差异'],
    cautionNotes: ['不使用已下线 renewal funnel/v2。'],
    forbiddenOutputs: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'claims_risk_diagnosis',
    name: '赔案风险诊断',
    supportLevel: 'supported',
    description: '分析未决、账龄、出险原因、理赔周期、地理风险、频度等。',
    coreMetrics: ['reported_claims', 'claim_cases', 'avg_claim_amount', 'earned_loss_frequency'],
    sourceEndpoints: ['/api/query/claims-detail/pending-overview', '/api/query/claims-detail/cause-analysis', '/api/query/claims-detail/frequency-yoy'],
    sourceTools: ['claims_detail.pending_overview', 'claims_detail.cause_analysis', 'claims_detail.frequency_yoy'],
    allowedUseCases: ['未决分析', '出险原因分析', '频度同比分析'],
    cautionNotes: ['ClaimsDetail 是当前数据视图，不替代完整准备金精算结论。'],
    forbiddenOutputs: ['承保利润', '财务盈利', '财务亏损'],
  },
  {
    id: 'customer_flow_diagnosis',
    name: '客户流向诊断',
    supportLevel: 'supported',
    description: '分析客户流入、流出和趋势。',
    coreMetrics: ['customer_inflow', 'customer_outflow', 'customer_flow_trend'],
    sourceEndpoints: ['/api/query/customer-flow/summary', '/api/query/customer-flow/inflow', '/api/query/customer-flow/outflow', '/api/query/customer-flow/trend', '/api/query/customer-flow/metadata'],
    sourceTools: ['customer_flow.summary', 'customer_flow.inflow', 'customer_flow.outflow', 'customer_flow.trend', 'customer_flow.metadata'],
    allowedUseCases: ['客户流入分析', '客户流失分析', '客户迁徙趋势'],
    cautionNotes: ['客户流向不直接代表利润。'],
    forbiddenOutputs: ['承保利润', '利润率', '财务盈利', '财务亏损'],
  },
  {
    id: 'comprehensive_cost_indicator_review',
    name: '综合费用/综合成本历史指标审阅',
    supportLevel: 'caution',
    description: '如果项目存在 comprehensiveCost，则仅作为历史经营指标审阅，不作为财务综合成本率 Agent。',
    coreMetrics: [
      'comprehensive_cost_ratio',
      'comprehensive_expense_ratio',
      'combined_cost_amount',
      'combined_cost_ratio',
      'fixed_cost_amount',
      'fixed_cost_ratio',
      'earned_claim_ratio',
      'expense_ratio',
      'variable_cost_ratio',
    ],
    sourceEndpoints: ['/api/query/cost'],
    sourceTools: ['cost.comprehensive_cost'],
    allowedUseCases: ['历史经营指标审阅', '与赔付率、费用率、变动成本率进行口径对照'],
    cautionNotes: ['必须显示口径警示。'],
    forbiddenOutputs: ['承保利润', '财务综合成本率', '盈亏判断', '利润率'],
    replacementSuggestions: ['经营成本压力请改看变动成本率、赔付率、费用率。'],
  },
  {
    id: 'renewal_funnel_diagnosis',
    name: '续保漏斗诊断',
    supportLevel: 'deprecated',
    description: '旧 renewal funnel/v2 已下线，不作为第一阶段 Agent 能力。',
    coreMetrics: [],
    sourceEndpoints: [],
    sourceTools: [],
    allowedUseCases: [],
    cautionNotes: ['请使用 renewal_tracker_diagnosis。'],
    forbiddenOutputs: ['继续路由到已下线路由'],
    replacementSuggestions: ['renewal_tracker_diagnosis'],
  },
  {
    id: 'renewal_v2_diagnosis',
    name: '续保 v2 诊断',
    supportLevel: 'deprecated',
    description: '旧 renewal v2 已下线，不作为第一阶段 Agent 能力。',
    coreMetrics: [],
    sourceEndpoints: [],
    sourceTools: [],
    allowedUseCases: [],
    cautionNotes: ['请使用 renewal_tracker_diagnosis。'],
    forbiddenOutputs: ['继续路由到已下线路由'],
    replacementSuggestions: ['renewal_tracker_diagnosis'],
  },
  {
    id: 'underwriting_profit_diagnosis',
    name: '承保利润诊断',
    supportLevel: 'unsupported',
    description: '当前项目不支持完整承保利润分析。',
    coreMetrics: [],
    sourceEndpoints: [],
    sourceTools: [],
    allowedUseCases: [],
    cautionNotes: ['缺少完整财务收入、准备金、再保、税费、固定费用分摊等口径。'],
    forbiddenOutputs: ['承保利润', '承保盈利', '承保亏损'],
    replacementSuggestions: ['cost_indicator_diagnosis', 'growth_diagnosis', 'quote_conversion_diagnosis', 'renewal_tracker_diagnosis', 'claims_risk_diagnosis'],
  },
  {
    id: 'profit_margin_diagnosis',
    name: '利润率诊断',
    supportLevel: 'unsupported',
    description: '当前项目不是完整财务利润系统。',
    coreMetrics: [],
    sourceEndpoints: [],
    sourceTools: [],
    allowedUseCases: [],
    cautionNotes: ['不能输出利润率、净利润或财务盈亏判断。边际贡献额应路由到成本指标诊断。'],
    forbiddenOutputs: ['利润率', '净利润', '盈利', '亏损'],
    replacementSuggestions: ['cost_indicator_diagnosis', 'forecast_operating_profit_scenario', 'growth_diagnosis'],
  },
  {
    id: 'financial_combined_ratio_diagnosis',
    name: '财务综合成本率诊断',
    supportLevel: 'unsupported',
    description: '当前项目不支持完整财务/精算口径综合成本率。',
    coreMetrics: [],
    sourceEndpoints: [],
    sourceTools: [],
    allowedUseCases: [],
    cautionNotes: ['可以使用项目内变动成本率、满期赔付率、费用率进行经营分析。'],
    forbiddenOutputs: ['财务综合成本率', '完整综合成本率', '承保综合成本率'],
    replacementSuggestions: ['cost_indicator_diagnosis', 'comprehensive_cost_indicator_review'],
  },
] satisfies AgentCapabilityDefinition[]);
