export const metricCapabilityMapping: Record<string, string[]> = {
  signed_premium: ['growth_diagnosis', 'business_patrol_diagnosis'],
  policy_count: ['growth_diagnosis', 'business_patrol_diagnosis', 'cost_indicator_diagnosis'],
  growth_rate: ['growth_diagnosis', 'business_patrol_diagnosis'],
  earned_premium: ['cost_indicator_diagnosis'],
  reported_claims: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
  claim_cases: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
  avg_claim_amount: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
  earned_claim_ratio: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
  earned_loss_frequency: ['cost_indicator_diagnosis', 'claims_risk_diagnosis'],
  expense_ratio: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
  variable_cost_ratio: ['cost_indicator_diagnosis', 'business_patrol_diagnosis'],
  earned_margin_amount: ['cost_indicator_diagnosis', 'comprehensive_cost_indicator_review'],
  projected_margin_amount: ['cost_indicator_diagnosis', 'comprehensive_cost_indicator_review'],
  forecast_operating_profit_amount: ['forecast_operating_profit_scenario'],
  quote_conversion_rate: ['quote_conversion_diagnosis', 'business_patrol_diagnosis'],
  renewal_tracker_metrics: ['renewal_tracker_diagnosis', 'business_patrol_diagnosis'],
  customer_inflow: ['customer_flow_diagnosis'],
  customer_outflow: ['customer_flow_diagnosis'],
  comprehensive_cost_ratio: ['comprehensive_cost_indicator_review'],
  expense_development_metrics: ['cost_indicator_diagnosis'],
};
