/**
 * 指标展示映射 — 从注册表自动生成
 *
 * 生成命令：bun scripts/metric-registry/generate-frontend-map.ts
 * 生成时间：2026-06-05T14:19:19.738Z
 * 指标数量：49
 *
 * ⚠ 不要手动编辑此文件，修改注册表后重新生成
 */

/** 指标 ID → 中文标签 */
export const METRIC_LABEL_MAP: Record<string, string> = {
  "total_premium": "总保费",
  "policy_count": "保单件数",
  "org_count": "机构数",
  "salesman_count": "业务员数",
  "per_capita_premium": "人均保费",
  "per_vehicle_premium": "车均保费",
  "transfer_rate": "过户占比",
  "telesales_rate": "电销占比",
  "renewal_rate": "续保占比",
  "commercial_rate": "商业险占比",
  "nev_rate": "新能源占比",
  "new_car_rate": "新车占比",
  "quality_business_rate": "优质业务占比",
  "commercial_insurance_rate": "商业险投保率",
  "underwriting_rate": "承保率",
  "earned_claim_ratio": "赔付率",
  "expense_ratio": "费用率",
  "avg_claim_amount": "案均赔款",
  "earned_premium": "满期保费",
  "baseline_premium": "基准保费",
  "baseline_earned_premium": "满期基准保费",
  "baseline_earned_claim_ratio": "满期基准赔付率",
  "variable_cost_ratio": "变动成本率",
  "earned_loss_frequency": "出险率",
  "earned_margin_amount": "满期边际贡献额",
  "projected_margin_amount": "预估边际贡献额",
  "comprehensive_expense_ratio": "综合费用率",
  "fixed_cost_amount": "固定成本额",
  "fixed_cost_ratio": "固定成本率",
  "combined_cost_amount": "综合成本额",
  "combined_cost_ratio": "综合成本率",
  "earned_profit_amount": "利润额",
  "bi_case_ratio_pct": "人伤案占比",
  "bi_amount_ratio_pct": "人伤金额占比",
  "cross_sell_total_rate": "推介率",
  "cross_sell_danjiao_rate": "单交推介率",
  "cross_sell_jiaosan_rate": "交三推介率",
  "cross_sell_zhuquan_rate": "主全推介率",
  "growth_rate_yoy": "同比增长率",
  "premium_growth_pct": "保费增长率",
  "growth_rate_mom": "环比增长率",
  "repair_shop_total_count": "合作网点数",
  "repair_4s_share": "4S 占比",
  "repair_cooperation_active_rate": "合作启用率",
  "repair_to_premium_ratio": "修保比",
  "repair_damage_amount_total": "维修产值",
  "repair_net_premium_total": "网点净保费",
  "plan_completion_pct": "计划达成率",
  "household_share_pct": "家自车占比",
} as const;

/** 指标 ID → 格式化配置 */
export const METRIC_FORMATTER_MAP: Record<string, {
  formatter: string;
  unit?: string;
  decimals?: number;
}> = {
  "total_premium": { formatter: "premiumWan", unit: "万元" },
  "policy_count": { formatter: "count", unit: "件" },
  "org_count": { formatter: "count", unit: "个" },
  "salesman_count": { formatter: "count", unit: "人" },
  "per_capita_premium": { formatter: "premiumWan", unit: "万元" },
  "per_vehicle_premium": { formatter: "average", unit: "元", decimals: 0 },
  "transfer_rate": { formatter: "percent", unit: "%" },
  "telesales_rate": { formatter: "percent", unit: "%" },
  "renewal_rate": { formatter: "percent", unit: "%" },
  "commercial_rate": { formatter: "percent", unit: "%" },
  "nev_rate": { formatter: "percent", unit: "%" },
  "new_car_rate": { formatter: "percent", unit: "%" },
  "quality_business_rate": { formatter: "percent", unit: "%" },
  "commercial_insurance_rate": { formatter: "percent", unit: "%" },
  "underwriting_rate": { formatter: "percent", unit: "%" },
  "earned_claim_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "expense_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "avg_claim_amount": { formatter: "premiumWan", unit: "万元" },
  "earned_premium": { formatter: "premiumWan", unit: "万元" },
  "baseline_premium": { formatter: "premiumWan", unit: "万元" },
  "baseline_earned_premium": { formatter: "premiumWan", unit: "万元" },
  "baseline_earned_claim_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "variable_cost_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "earned_loss_frequency": { formatter: "percent", unit: "%", decimals: 1 },
  "earned_margin_amount": { formatter: "premiumWan", unit: "万元" },
  "projected_margin_amount": { formatter: "premiumWan", unit: "万元" },
  "comprehensive_expense_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "fixed_cost_amount": { formatter: "premiumWan", unit: "万元" },
  "fixed_cost_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "combined_cost_amount": { formatter: "premiumWan", unit: "万元" },
  "combined_cost_ratio": { formatter: "percent", unit: "%", decimals: 1 },
  "earned_profit_amount": { formatter: "premiumWan", unit: "万元" },
  "bi_case_ratio_pct": { formatter: "percent", unit: "%", decimals: 1 },
  "bi_amount_ratio_pct": { formatter: "percent", unit: "%", decimals: 1 },
  "cross_sell_total_rate": { formatter: "percent", unit: "%", decimals: 2 },
  "cross_sell_danjiao_rate": { formatter: "percent", unit: "%", decimals: 2 },
  "cross_sell_jiaosan_rate": { formatter: "percent", unit: "%", decimals: 2 },
  "cross_sell_zhuquan_rate": { formatter: "percent", unit: "%", decimals: 2 },
  "growth_rate_yoy": { formatter: "percent", unit: "%", decimals: 2 },
  "premium_growth_pct": { formatter: "percent", unit: "%", decimals: 2 },
  "growth_rate_mom": { formatter: "percent", unit: "%", decimals: 2 },
  "repair_shop_total_count": { formatter: "count", unit: "个" },
  "repair_4s_share": { formatter: "percent", unit: "%" },
  "repair_cooperation_active_rate": { formatter: "percent", unit: "%" },
  "repair_to_premium_ratio": { formatter: "coefficient", unit: "倍", decimals: 3 },
  "repair_damage_amount_total": { formatter: "premiumWan", unit: "万元" },
  "repair_net_premium_total": { formatter: "premiumWan", unit: "万元" },
  "plan_completion_pct": { formatter: "percent", unit: "%", decimals: 2 },
  "household_share_pct": { formatter: "percent", unit: "%", decimals: 2 },
} as const;

/** 指标 ID → 公式描述 */
export const METRIC_FORMULA_MAP: Record<string, string> = {
  "total_premium": "所有保单保费之和",
  "policy_count": "去重保单计数",
  "org_count": "去重三级机构计数",
  "salesman_count": "去重业务员计数",
  "per_capita_premium": "保费总额 / 业务员数",
  "per_vehicle_premium": "保费总额 / 去重车架号数（含商业险+交强险）",
  "transfer_rate": "过户保单数 / 总保单数",
  "telesales_rate": "电销保单数 / 总保单数",
  "renewal_rate": "续保保单数 / 总保单数",
  "commercial_rate": "商业保险保费 / 总保费",
  "nev_rate": "新能源车保单数 / 总保单数",
  "new_car_rate": "新车保单数 / 总保单数",
  "quality_business_rate": "优质业务保单数 / 总保单数",
  "commercial_insurance_rate": "商业险件数 / 交强险件数",
  "underwriting_rate": "承保件数 / 报价件数（单据级）",
  "earned_claim_ratio": "已报告赔款 / 满期保费（闰年感知）",
  "expense_ratio": "费用金额 / 签单保费（保单明细域 fee_amount，不混同综合费用率/综合成本率）",
  "avg_claim_amount": "已报告赔款 / 赔案件数",
  "earned_premium": "保费 × 满期天数 / 保险期限天数（闰年感知）",
  "baseline_premium": "基准保费：商业险按商车自主定价系数归一，非商业险保持原保费",
  "baseline_earned_premium": "满期基准保费 = 基准保费 × 满期天数 / 保险期限天数（闰年感知）",
  "baseline_earned_claim_ratio": "满期基准赔付率 = 已报告赔款 / 满期基准保费",
  "variable_cost_ratio": "满期赔付率 + 费用率（两个分母不同；闰年感知）",
  "earned_loss_frequency": "(赔案件数/保单件数) × (保险期限天数/满期天数)。满期后=赔案/保单，未满期年化放大",
  "earned_margin_amount": "满期保费 × (1 - 已报告赔款/满期保费 - 费用金额/签单保费)（闰年感知）",
  "projected_margin_amount": "签单保费 × (1 - 已报告赔款/满期保费 - 费用金额/签单保费)（闰年感知）",
  "comprehensive_expense_ratio": "(已报告赔款 + 费用金额) / 满期保费（闰年感知）",
  "fixed_cost_amount": "附加税费额 + 推动费额 + 管理费额（均为绝对值聚合）",
  "fixed_cost_ratio": "固定成本额 / 满期保费",
  "combined_cost_amount": "变动成本额 + 固定成本额 = 已报告赔款 + 费用金额 + 固定成本额",
  "combined_cost_ratio": "综合成本额 / 满期保费（绝对值除法，非率值相加）",
  "earned_profit_amount": "满期保费 - 综合成本额 = 边际贡献额 - 固定成本额",
  "bi_case_ratio_pct": "人伤案件数 / 总案件数（claims_detail 底表）",
  "bi_amount_ratio_pct": "(人伤已决 + 人伤未决) / (总已决 + 总未决)（claims_detail 底表）",
  "cross_sell_total_rate": "驾意险件数 / 车险件数",
  "cross_sell_danjiao_rate": "单交下驾意险件数 / 单交车险件数",
  "cross_sell_jiaosan_rate": "交三下驾意险件数 / 交三车险件数",
  "cross_sell_zhuquan_rate": "主全下驾意险件数 / 主全车险件数",
  "growth_rate_yoy": "(本期 - 去年同期) / 去年同期",
  "premium_growth_pct": "(本期签单保费 − 去年同期签单保费) × 100 ÷ 去年同期签单保费",
  "growth_rate_mom": "(本期 - 上期) / 上期",
  "repair_shop_total_count": "RepairDim 中排除非维修单位后的去重网点数",
  "repair_4s_share": "4S 店网点数 / 有效合作网点数",
  "repair_cooperation_active_rate": "已合作（1生效中）网点数 / 有效合作网点数",
  "repair_to_premium_ratio": "维修产值（核损金额）/ 签单净保费；衡量合作深度",
  "repair_damage_amount_total": "所有网点核损金额合计（= 维修产值）",
  "repair_net_premium_total": "RepairDim 中所有网点签单净保费合计",
  "plan_completion_pct": "实际签单保费 × 100 ÷ (年计划保费 × 时间进度)",
  "household_share_pct": "客户类别='非营业个人客车' 的保单数 × 100 ÷ 全部保单数",
} as const;
